# Generated by Django 5.1.5 on 2025-02-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WinnerMatchDetails',
        ),
    ]
