# Generated by Django 5.1.5 on 2025-02-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0002_delete_winnermatchdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerMatchDetails',
            fields=[
                ('winnerMatchID', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictiveplayapp.match')),
                ('mostrunsplayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_runs_player', to='predictiveplayapp.player')),
                ('mostwickettaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_wickets_taker', to='predictiveplayapp.player')),
                ('playerofmatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_of_match', to='predictiveplayapp.player')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to='predictiveplayapp.team')),
            ],
        ),
    ]
