# Generated by Django 5.1.5 on 2025-02-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0004_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='leaderboardScores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userScores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerRole',
            field=models.IntegerField(choices=[(0, 'Batsman'), (1, 'Bowler'), (2, 'AllRounder')]),
        ),
    ]
