# Generated by Django 5.1.5 on 2025-02-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0005_submission_leaderboardscores_userinfo_userscores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='leaderboardScores',
            new_name='submissionScores',
        ),
    ]
