# Generated by Django 5.1.5 on 2025-02-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0006_rename_leaderboardscores_submission_submissionscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='predictiveplayapp.crickettournament'),
        ),
    ]
