# Generated by Django 5.1.5 on 2025-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictiveplayapp', '0007_leaderboard_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='leaderboardName',
            field=models.CharField(max_length=32),
        ),
    ]
